### ISSUE TITLE
K-means algorithm

### ISSUE THREAD

**Issue by Bhasfe** [Bhasfe/ml-algorithms#1]
**K-means algorithm is needed to be added.**

1. It should be implemented in a single Jupyter Notebook. Algorithm. The notebook should be in a proper folder, it should contain **Introduction**, **explanation**, **EDA**, **FE** (if necessary), and the **model** sections. You can look at other notebooks that I added to the repository.
2. If you need a dataset that is not in the repository. You can upload it to `ml-algorithms/datasets/`. Don't forget to give the source of the dataset in `Sources.txt`

**Comment by nipendra** [comment]
I want to work on it

**Comment by Bhasfe** [comment]
Sure, you can work

**Comment by jainriya9** [comment]
Greetings!

I can add the K-means Algorithm. I have worked on ML projects earlier. Kindly assign me this issue. Looking forward to contribute!

Thankyou so much!
@Bhasfe

**Comment by Bhasfe** [comment]
Hi, @jainriya9 sure, I assigned you

**Comment by jainriya9** [comment]
> Hi, @jainriya9 sure, I assigned you

I can work on any dataset of my choice right?
Thanks

**Comment by jainriya9** [comment]
> Hi, @jainriya9 sure, I assigned you

I have created the PR. 
Thankyou!
@Bhasfe

**Comment by Bhasfe** [comment]
closed with https://github.com/Bhasfe/ml-algorithms/pull/10
